<?php
/**
 * 番組診断ページ
 * Template Name: 番組診断
 */
get_header();
?>

<section class="section shindan" id="shindan">
    <!-- Step: Intro -->
    <div class="shindan-step shindan-intro is-active" data-step="intro">
        <div style="text-align: center; padding: var(--space-xl) var(--space-md);">
            <span style="font-size: 3rem;"><?php echo koi_ria_icon('sparkle', 40); ?></span>
            <h1 style="margin-top: var(--space-md); font-size: 1.375rem;">あなたにぴったりの<br>恋リアは？</h1>
            <p style="margin-top: var(--space-sm); color: var(--color-text-sub); font-size: 0.875rem;">5つの質問に答えるだけ！</p>
            <button class="btn btn--primary" id="shindanStart" style="margin-top: var(--space-lg);">診断スタート</button>
        </div>
    </div>

    <!-- Step: Questions (generated by JS) -->
    <div class="shindan-step shindan-questions" data-step="questions" style="display:none;">
        <div class="shindan-progress" style="padding: var(--space-md);">
            <div class="shindan-progress__bar">
                <div class="shindan-progress__fill" id="shindanProgress" style="width: 20%;"></div>
            </div>
            <span class="shindan-progress__text" id="shindanProgressText">Q1 / 5</span>
        </div>
        <div id="shindanQuestion" style="padding: var(--space-md);"></div>
    </div>

    <!-- Step: Result (generated by JS) -->
    <div class="shindan-step shindan-result" data-step="result" style="display:none;">
        <div id="shindanResult" style="text-align: center; padding: var(--space-xl) var(--space-md);"></div>
    </div>
</section>

<?php get_footer(); ?>
